### ISSUE TITLE
This plugin has 0 goal

### ISSUE THREAD

**Issue by sewolf** [Swagger2Markup/swagger2markup-maven-plugin#16]
Hi,

there is an error with v 0.9.2 with maven:

mvn swagger2markup:process-swagger

 Could not find goal 'process-swagger' in plugin io.github.robwin:swagger2markup-maven-plugin:0.9.2 among available goals

mvn help:describe -Ddetail -Dplugin=swagger2markup

[INFO] io.github.robwin:swagger2markup-maven-plugin:0.9.2

Name: Swagger2Markup Maven Plugin
Description: Swagger2Markup Maven Plugin
Group Id: io.github.robwin
Artifact Id: swagger2markup-maven-plugin
Version: 0.9.2
Goal Prefix: swagger2markup

This plugin has 0 goal:

---
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/sewolf/tools/apache-maven
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle-1.8.0.66/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"

**Comment by RobWin** [comment]
Yes, there is an issue atm. Please use the old version until it works:

```
plugins>
  <plugin>
    <groupId>com.redowlanalytics</groupId>
    <artifactId>swagger2markup-maven-plugin</artifactId>
    <version>0.7.1</version>
  </plugin>
</plugins>
```

**Comment by atomfrede** [comment]
@RobWin We've deployed the current war file in our artifactory and it works fine now. Maybe you could publish a 0.9.2.1-SNAPSHOT in order to test it from central or bintray (don't know how much effort that is)

**Comment by sg-ad** [comment]
Hi, any idea when the new version will become available?  I really need the recent feature for specifying the `swaggerFile` parameter, but can't currently use it.  Thanks!

**Comment by sg-ad** [comment]
FYI, for anybody who might need a workaround in the meantime: build the plugin and publish to your local maven repository.  Cheers!

**Comment by RobWin** [comment]
I don't have time to test the plugin atm. But if someone can test it, I can release a new version.

**Comment by atomfrede** [comment]
I can have a look in our artifactory today. I published the generated jar file to it and works very well. Need to check if it was the jar created via gradle (``publishMavenLocal``) or the one created via maven.

**Comment by atomfrede** [comment]
@RobWin I've checked our current deployment. I needed to deploy the jar generated by maven. The via gradle created jar file doesn't contain the required pom. The pom is deployed aside the jar file in local m2 repository. I don't know if thats a problem for your bintray publish task.

**Comment by nrekretep** [comment]
Hi there! Any news on this issue? I tried the older version 0.7.1 but it does not seem to support the <pathsGroupedBy> configuration switch like the cli version does.

**Comment by RobWin** [comment]
I just need some help fixing the Maven or Gradle build.

**Comment by RobWin** [comment]
I published version 0.9.3.

`io.github.robwin:swagger2markup-maven-plugin:0.9.3`


Could you please check if it is working for you?

**Comment by atomfrede** [comment]
@RobWin works fine!

**Comment by RobWin** [comment]
Great. Can I close the issue then?

**Comment by atomfrede** [comment]
Yes.

**Comment by atomfrede** [comment]
I guess #2 can be closed too?

**Comment by RobWin** [comment]
Done
