### ISSUE TITLE
$ref support for local files

### ISSUE THREAD

**Issue by Kabhal** [Swagger2Markup/swagger2markup-maven-plugin#17]
Hello,

I'm using $ref in swagger main file to include an external file like this :
```
swagger: '2.0'  
info:  
  $ref: ./info.yaml  
...
```

info.yaml is in the same directory that the swagger file.

However, the generated markup overview.md fails to display the informations.
Is $ref supported this way ?

**Comment by RobWin** [comment]
Yes, should be. But this is a question you should ask in https://github.com/swagger-api/swagger-parser.
I just use the resulting Swagger Model. Resolving of files is done by the parser.

**Comment by Kabhal** [comment]
It seems there are a lot of problems with $ref in swagger-parser, and a lot of locations $ref is not correctly  managed so the problem is definitively there :)
