### ISSUE TITLE
Support for separateOperations configuration

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup-maven-plugin#20]
Hi,

Are there any plans to expose the new separateOperations configuration from swagger 2 markup through the maven plug in? I could certainly look at adding this option as it seems a straight pass through like separateDefinitions?

Thanks

**Comment by RobWin** [comment]
Hi,

its only part of 1.0.0-SNAPSHOT. You can test the new plugin. See docs:  http://swagger2markup.github.io/swagger2markup/1.0.0-SNAPSHOT/

If you like Swagger2markup, we would love to get your GitHub Stars.

**Comment by mattadamson** [comment]
Thanks Robert,

I followed the documents and configured the repositories element and changed the reference. Whilst building we see this error

[ERROR] Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plu
gin:1.0.0-SNAPSHOT:convertSwagger2markup (default-cli) on project testa: Executi
on default-cli of goal io.github.swagger2markup:swagger2markup-maven-plugin:1.0.
0-SNAPSHOT:convertSwagger2markup failed: A required class was missing while exec
uting io.github.swagger2markup:swagger2markup-maven-plugin:1.0.0-SNAPSHOT:conver
tSwagger2markup: org/apache/commons/configuration2/Configuration
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.github.swagger2markup:swagger2markup-maven-plugin:1
.0.0-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/madamson/.m2/repository/io/github/swagger2marku
p/swagger2markup-maven-plugin/1.0.0-SNAPSHOT/swagger2markup-maven-plugin-1.0.0-S
NAPSHOT.jar
[ERROR] urls[1] = file:/C:/Users/madamson/.m2/repository/io/github/swagger2marku
p/swagger2markup/1.0.0-SNAPSHOT/swagger2markup-1.0.0-SNAPSHOT.jar
[ERROR] urls[2] = file:/C:/Users/madamson/.m2/repository/io/github/swagger2marku
p/markup-document-builder/1.0.0-SNAPSHOT/markup-document-builder-1.0.0-SNAPSHOT.
jar

**Comment by RobWin** [comment]
Could you also please add Maven Central to your list of repositories and retry?

**Comment by RobWin** [comment]
Can you have a look at https://github.com/Swagger2Markup/swagger2markup-maven-project-template/blob/s2m-1.0.0/pom.xml

**Comment by mattadamson** [comment]
Thanks Robert, let's focus on that project and get it working first. I just imported and got this 

Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find
 artifact nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0 in central
 (http://repo.maven.apache.org/maven2)
        at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$6.wrap(Wa
gonRepositoryConnector.java:1012)
        at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$6.wrap(Wa
gonRepositoryConnector.java:1004)
        at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.r
un(WagonRepositoryConnector.java:725)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(Runn
ableErrorForwarder.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)

**Comment by RobWin** [comment]
Thx. I fix that on monday and add a TravisCI Build. The issue here is that markdown_to_asciidoc is only available on Jcentral. I asked them to publish it on Maven Central as well.

**Comment by RobWin** [comment]
I think i have to change repositories to pluginRepositories in the pom.xml so that it works.

**Comment by mattadamson** [comment]
Thanks. If I can help in anyway to publish it let me know or try something locally

**Comment by mattadamson** [comment]
I also tried moving the repositories defined into a pluginRepositories element and got this

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/configuration2/Con
figuration
        at io.github.swagger2markup.Swagger2MarkupMojo.execute(Swagger2MarkupMoj
o.java:62)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:106)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration2.C
onfiguration
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(
SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm

**Comment by RobWin** [comment]
Ok. So its your original issue now.
Apache Commons Configuration 2 is a transitive dependency of Swaggger2Markup. Could you please add Maven Central to the list of pluginRepositories now?

**Comment by mattadamson** [comment]
Still the same error. This is what I have in the section now from the example pom

		<pluginRepositories>
			<pluginRepository>
				<id>jcenter-snapshots</id>
				<name>jcenter</name>
				<url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
			</pluginRepository>
			<pluginRepository>
				<snapshots>
					<enabled>false</enabled>
				</snapshots>
				<id>jcenter-releases</id>
				<name>jcenter</name>
				<url>http://jcenter.bintray.com</url>
			</pluginRepository>
			<pluginRepository>
				<snapshots>
					<enabled>true</enabled>
				</snapshots>
				<id>central</id>
				<name>Central Repository</name>
				<url>https://repo.maven.apache.org/maven2</url>
			</pluginRepository>
		</pluginRepositories>


I also tried with snapshots enabled / disabled in the maven central element

**Comment by RobWin** [comment]
Unfortunately I can't reproduce it in TravisCI. TravisCI can download all dependencie and the goal `mvn swagger2markup:convertSwagger2markup` works.

https://travis-ci.org/Swagger2Markup/swagger2markup-maven-project-template/builds/122182373

**Comment by mattadamson** [comment]
Thanks Robert, this appears to now be a proxy issue however we can simply close this issue.  Are there any plans to release version 1.0.0.0 officially soon?

**Comment by RobWin** [comment]
I think within this month
