### ISSUE TITLE
Reference documentation link broken

### ISSUE THREAD

**Issue by carlosjgp** [Swagger2Markup/swagger2markup-maven-plugin#22]
https://swagger2markup.readme.io/

**Comment by RobWin** [comment]
Thx. It's http://swagger2markup.github.io/swagger2markup/1.0.0/ now.

**Comment by vcrm** [comment]
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**Comment by RobWin** [comment]
yes. Thx. I have to fix the gh-pages deployment of the documentation.
