### ISSUE TITLE
Soporte a proceso de multiples archivos (swaggerInput parameter)

### ISSUE THREAD

**Issue by arielcarrera** [Swagger2Markup/swagger2markup-maven-plugin#23]
Older versions (0.8 or minor) have an option for iterate over multiple swagger files setting into a directory.
Why this option is not present in last versions?

**Comment by RobWin** [comment]
Multiple input files caused issues when you want to use Swagger2Markup extensions. That's why we decided that we can't support it anymore.
But you can create a multi-module Maven project and convert multiple files that way.
