### ISSUE TITLE
v1.0.0 not working: Could not find artifact nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0

### ISSUE THREAD

**Issue by afdia** [Swagger2Markup/swagger2markup-maven-plugin#25]
Hi

When I am changing the plugin version from 0.9.3 to 1.0.0 (with the necessary changes to the configuration and the goal according to the sourcecode of the class) I get the following error:

[ERROR] Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.0.0:convertSwagger2markup (gen-asciidoc) on project admin: Execution gen-asciidoc of goal io.github.swagger2markup:swagger2markup-maven-plugin:1.0.0:convertSwagger2markup failed: Plugin io.github.swagger2markup:swagger2markup-maven-plugin:1.0.0 or one of its dependencies could not be resolved: Could not find artifact nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

After checking https://mvnrepository.com/artifact/io.github.swagger2markup/markup-document-builder/1.0.0 it seems to be correct that the dependency is missing (if you click on it in the section **Compile Dependencies**, you get a 404: https://mvnrepository.com/artifact/nl.jworks.markdown_to_asciidoc/markdown_to_asciidoc)

There have been major changes so perhaps I'm just doing something wrong, but here are the examples I used; the working 0.9.3 example and the not working 1.0.0 example:

```
<plugin>
	<groupId>io.github.robwin</groupId>
	<artifactId>swagger2markup-maven-plugin</artifactId>
	<version>0.9.3</version>
	<executions>
		<execution>
			<id>gen-asciidoc</id>
			<phase>process-classes</phase>
			<goals>
				<goal>process-swagger</goal>
			</goals>
			<configuration>
				<inputDirectory>${project.basedir}/target/apidocs-rest/swagger</inputDirectory>
				<outputDirectory>${project.basedir}/target/apidocs-rest/asciidoc</outputDirectory>
			</configuration>
		</execution>
	</executions>
</plugin>
```
```
<plugin>
	<groupId>io.github.swagger2markup</groupId>
	<artifactId>swagger2markup-maven-plugin</artifactId>
	<version>1.0.0</version>
	<executions>
		<execution>
			<id>gen-asciidoc</id>
			<phase>process-classes</phase>
			<goals>
				<goal>convertSwagger2markup</goal>
			</goals>
			<configuration>
				<swaggerInput>${project.basedir}/target/apidocs-rest/swagger</swaggerInput>
				<outputDir>${project.basedir}/target/apidocs-rest/asciidoc</outputDir>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by afdia** [comment]
oh sorry I've just seen that you already reported the problem at https://github.com/bodiam/markdown-to-asciidoc/issues/26

The reason for the upgrade to v1.0.0 would be the possibility to use the <config> tag for all possible configuration keys. Is there a way to do it with 0.9.3 or do you plan to add the <config> tag for a version without the missing dependency?

**Comment by RobWin** [comment]
Hi,

please have a look at the documentation: http://swagger2markup.github.io/swagger2markup/1.0.1-SNAPSHOT/#_maven_plugin

You also need the Bintray repo.
You can check the swagger2markup-maven-template-project.

**Comment by afdia** [comment]
Thanks, it works with the JCenter repository.

Perhaps you could change the link to the reference documentation on the main page of the maven plugin to the url with the anchor.
From: http://swagger2markup.github.io/swagger2markup/1.0.1-SNAPSHOT/
To: http://swagger2markup.github.io/swagger2markup/1.0.1-SNAPSHOT/#_maven_plugin

I have seen the link, but though it's just the general swagger2markup documentation without scrolling far enough down to see the maven plugin specific part and example (my fault, but the anchor would have helped me ;) )
And the main page still says JDK 7 is required while the documentation says JDK 8.

Anyways, thanks for the great tools! :)
