### ISSUE TITLE
swagger2markup.extensions.dynamicOverview seems not to work

### ISSUE THREAD

**Issue by holtermp** [Swagger2Markup/swagger2markup-maven-plugin#28]
Hi @RobWin ,
Im using  <swagger2markup-maven-plugin</artifactId 1.1.0 which is working quite nicely in creating asciidoc and pdfs from the swagger doc of our REST-Service as a part of the maven build.

Now Id like to add some custom introductory text to the documentation.
I added
`<swagger2markup.extensions.dynamicOverview.contentPath>D:\data\pu-trunk\ws-inbound\pu-inbound-webservice-ibe\src/docs/asciidoc/extensions/overview</swagger2markup.extensions.dynamicOverview.contentPath>
`
to the configuration section in my pom.xml

I added a file called    `D:\data\pu-trunk\ws-inbound\pu-inbound-webservice-ibe/src/docs/asciidoc/extensions/overview/document-begin-intro.adoc` containing some sample asciidoc:
> = Example Abstract
> The optional abstract (one or more paragraphs) goes here.
> This document is an AsciiDoc article skeleton containing briefly
> annotated element placeholders plus a couple of example index entries
> and footnotes.

But when i run maven no text is added to the generated asciidoc files and consequently to the resulting pdf. It looks as if the file is never picked up by the plugin. The rest of the generation works fine.

I can see the configuration option properly read by the plugin:
`[DEBUG] swagger2markup.extensions.dynamicOverview.contentPath: D:\data\pu-trunk\ws-inbound\pu-inbound-webservice-ibe\src/docs/asciidoc/extensions/overview`

I am sure I am missing something here, Can you help me? Thanks a lot,
Peter

**Comment by RobWin** [comment]
Hi,

thx for using Swagger2Markup. If you like it, we would love to get your GitHub Stars.
What if move your files into the Project. Similar to the template project? https://github.com/Swagger2Markup/swagger2markup-maven-project-template

**Comment by RobWin** [comment]
You can also add manual content with include directives in your index.adoc.
See https://raw.githubusercontent.com/Swagger2Markup/swagger2markup-maven-project-template/master/src/docs/asciidoc/index.adoc

**Comment by holtermp** [comment]
Thanks, that was fast.
I tried the index.adoc  but that did not work either. Should I see anything in the maven log, if I run that with the debug option?

I think I will just clone the template prroject and see if i can get that to work. If that works, I will probably be able to figure out what the problem is with my problem.
Thanks again

**Comment by holtermp** [comment]
After messing around with the template project, I finally understood that the index.adoc does not really have anything to do with the swagger2markup-maven-plugin nut with the following asciidoctor-maven-plugin step. This was not converting index.adoc but a custom adoc-file supplied by our buildteam, which referenced the parts generated by swagger2markup.

Thus no changes in index.adoc made it into the pdf....
I stell cannot figure out why the dynamicOverview stuff does not work, but that is no longer an issue, as index.adoc mechanism is sufficient for my needs.
Thx.

**Comment by RobWin** [comment]
👍
