### ISSUE TITLE
hello,there is a question that when I compile swagger2markup-maven-plugin project but the file of target doesn't have the class of Swagger2MarkupMojo

### ISSUE THREAD

**Issue by jymf** [Swagger2Markup/swagger2markup-maven-plugin#29]

**Comment by RobWin** [comment]
Hello,

could you please take your time and create a meaningful issue.
Could you please paste your exception?

**Comment by jymf** [comment]
sorry,I find the answer.  My jdk's version is 1.7 and swagger2markup-maven-plugin's jdk is 1.8. I change it with 1.8  and the problem is resolved.   I'm so sorry to take your time.  
With your code , I can get what I want . The plugin is so greate. But our company's projects are all 1.7,  in order to cooperate with other projects effectively, we have to use the 1.7 version. But I want to use the swagger functions with my project that will help us a lot, so could you give me a suggestion?  I'm very grateful for youe help.

**Comment by RobWin** [comment]
If you like Swagger2Markup, we would love to get your GitHub star here: https://github.com/Swagger2Markup/swagger2markup

Regarding your JDK8 issue, you could create a Swagger.yaml file with JDK7 and convert the Swagger file into AsciiDoc in a separate JVM process using JDK8.

**Comment by jymf** [comment]
ok,I will try later. thank you.
Now I use 1.8 and meet a problem in my project .
 I compile it and it says "[ERROR] Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.1.1-SNAPSHOT:convertSwagger2markup (default) on project peraudit-webapp: Failed to execute goal 'convertSwagger2markup': swaggerPath does not exist: ***\target\swagger\swagger.json -> [Help 1]",  I use the plugin as follows:
<properties>
    <swagger.input>${project.build.directory}/swagger/swagger.json</swagger.input>
</properties>
 <plugin>
                <groupId>io.github.swagger2markup</groupId>
                <artifactId>swagger2markup-maven-plugin</artifactId>
                <version>1.1.1-SNAPSHOT</version>
                <dependencies>
                    <dependency>
                        <groupId>io.github.swagger2markup</groupId>
                        <artifactId>swagger2markup-import-files-ext</artifactId>
                        <version>${swagger2markup.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>io.github.swagger2markup</groupId>
                        <artifactId>swagger2markup-spring-restdocs-ext</artifactId>
                        <version>${swagger2markup.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <swaggerInput>${swagger.input}</swaggerInput>
                    <outputDir>${generated.asciidoc.directory}</outputDir>
                    <config>
                        <swagger2markup.markupLanguage>ASCIIDOC</swagger2markup.markupLanguage>
                        <swagger2markup.pathsGroupedBy>TAGS</swagger2markup.pathsGroupedBy>

                        <swagger2markup.extensions.dynamicOverview.contentPath>${project.basedir}/src/docs/asciidoc/extensions/overview</swagger2markup.extensions.dynamicOverview.contentPath>
                        <swagger2markup.extensions.dynamicDefinitions.contentPath>${project.basedir}/src/docs/asciidoc/extensions/definitions</swagger2markup.extensions.dynamicDefinitions.contentPath>
                        <swagger2markup.extensions.dynamicPaths.contentPath>${project.basedir}/src/docs/asciidoc/extensions/paths</swagger2markup.extensions.dynamicPaths.contentPath>
                        <swagger2markup.extensions.dynamicSecurity.contentPath>${project.basedir}src/docs/asciidoc/extensions/security/</swagger2markup.extensions.dynamicSecurity.contentPath>

                        <swagger2markup.extensions.springRestDocs.snippetBaseUri>${swagger.snippetOutput.dir}</swagger2markup.extensions.springRestDocs.snippetBaseUri>
                        <swagger2markup.extensions.springRestDocs.defaultSnippets>false</swagger2markup.extensions.springRestDocs.defaultSnippets>
                    </config>
                </configuration>
                <executions>
                    <execution>
                        <phase>test</phase>
                        <goals>
                            <goal>convertSwagger2markup</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
I don't know where the problem is,I have defined the swaggerInput path.
