### ISSUE TITLE
Maven plugin is not keeping up with the swagger2markup releases

### ISSUE THREAD

**Issue by jbrugge** [Swagger2Markup/swagger2markup-maven-plugin#30]
I see that swagger2markup has now released v1.2.0, but the most recent release of the Maven plugin is still only supporting v1.1.0.

**Comment by RobWin** [comment]
The Plugin is not coupled to a specific Swagger2markup version.
You can use the plugin v1.1.0 with Swagger2Markup v1.2.0

See https://github.com/Swagger2Markup/swagger2markup-maven-project-template/blob/master/pom.xml#L58

Anyway I will update the plugin soon.

**Comment by jbrugge** [comment]
Aha, thanks for the pointer.
