### ISSUE TITLE
Publishing problem

### ISSUE THREAD

**Issue by atomfrede** [Swagger2Markup/swagger2markup-maven-plugin#32]
Hi,

I have tried to upgrade https://github.com/atomfrede/generator-jhipster-swagger2markup to the latest swagger2markup version. For gradle everything worked fine 👍 

When I updated maven and the plugin to `1.3.1` I get the following error:

```
[WARNING] Failed to retrieve plugin descriptor for io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1: Invalid plugin descriptor for io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1 
```

When looking at the downloaded `swagger2markup-maven-plugin-1.3.1.jar` file the `plugin.xml` contains indeed `<version>1.0.1</version>`. So something seems incorrect here :) The problem is there when using central and when using jcenter repository.

**Comment by RobWin** [comment]
Thx. Grrr I don't like Maven :P

**Comment by RobWin** [comment]
I've overwritten the existing 1.3.1 in Bintry.
Could you please try again?

**Comment by atomfrede** [comment]
Will try this evening and keep you updated here.

**Comment by RobWin** [comment]
thx

**Comment by atomfrede** [comment]
@RobWin Work fine now, thanks!
