### ISSUE TITLE
Invalid plugin descriptor for version 1.3.2?

### ISSUE THREAD

**Issue by roltean** [Swagger2Markup/swagger2markup-maven-plugin#34]
Hi,

I'm getting this exception when trying to build a project using the plugin in Jenkins:

**`[ERROR] Invalid plugin descriptor for io.github.swagger2markup:swagger2markup-maven-plugin:1.3.2 (/data/jenkins/jobs/project/workspace/.repository/io/github/swagger2markup/swagger2markup-maven-plugin/1.3.2/swagger2markup-maven-plugin-1.3.2.jar), Plugin's descriptor contains the wrong version: 1.3.1 -> [Help 1]`**

Any thoughts?

**Comment by pikus** [comment]
Thart's because some dynamically generated files are stored in git (https://github.com/Swagger2Markup/swagger2markup-maven-plugin/tree/master/src/main/resources/META-INF/maven) so they needs to be manually adjusted during release.

**Comment by roltean** [comment]
I think the problem is fixed now. Not sure what happened initially. Closing the issue.
