### ISSUE TITLE
Invalid plugin descriptor error on Release 1.3.2

### ISSUE THREAD

**Issue by sumeetchhikara** [Swagger2Markup/swagger2markup-maven-plugin#35]
I've checked 1.3.2 jar and plugin.xml contains version 1.3.1 and hence the validation error.
This could be due to 2 separate commits were made for release 1.3.2.

Here is the error --
`[ERROR] Invalid plugin descriptor for io.github.swagger2markup:swagger2markup-maven-plugin:1.3.2 (/Users/sumeet/.m2/repository/io/github/swagger2markup/swagger2markup-maven-plugin/1.3.2/swagger2markup-maven-plugin-1.3.2.jar), Plugin's descriptor contains the wrong version: 1.3.1 -> [Help 1]`

**Comment by RobWin** [comment]
Thx. I publish a new release when I'm back from vacation. In the meantime please use v1.3.1

**Comment by RobWin** [comment]
Hi,
could you please clean your local maven repo
`rm -rf  ~/.m2/repository/io/github/swagger2markup/swagger2markup-maven-plugin/1.3.2` and then execute the swagger2markup goal again.
Maven Central contained an old buggy version. I've fixed it.

**Comment by anejnz** [comment]
Hi,

how do we get the fixed version, have removed the local jar from my m2 but still end up downloading the buggy version from Maven Central

cheers
Anej

**Comment by RobWin** [comment]
Do you use a private nexus as a proxy?

**Comment by anejnz** [comment]
I think you should just release a 1.3.3 to keep it simple

**Comment by RobWin** [comment]
Done. I release v.1.3.3

**Comment by marcelstoer** [comment]
Guess this should be closed?
