### ISSUE TITLE
POST parameters missing

### ISSUE THREAD

**Issue by tdtappe** [Swagger2Markup/swagger2markup-maven-plugin#36]
I've got some post request like this

```
      "post" : {
        "summary" : "getMeasuringPoint",
        "description" : "Measuring point object for the provided measuring point id",
        "operationId" : "getMeasuringPoint",
        "parameters" : [ {
          "name" : "id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/MeasuringPoint"
            }
          }
        }
      }
```
but the resulting adoc does not contain any parameters:
```
[[_getmeasuringpoint]]
=== getMeasuringPoint
....
POST /MeasuringPointService/getMeasuringPoint
....


==== Description
Measuring point object for the provided measuring point id


==== Responses

[options="header", cols=".^2,.^14,.^4"]
|===
|HTTP Code|Description|Schema
|**200**|successful operation|<<_measuringpoint,MeasuringPoint>>
|===
```

I does work with GETs though. What am I doing wrong?
I am using version 1.3.3 of the swagger2markup maven plugin with no further configuration than asciidoc as markup language.

--Heiko

**Comment by RobWin** [comment]
Are you using Swagger Spec v2 or v3?
As far as I can see, your parameter is missing the location. The location is determined by the parameter’s `in` key, for example, `in: query` or `in: path`.

**Comment by tdtappe** [comment]
Oh, of course. Stupid me :-S
Works like a charm now - thanks a lot!

Another thing (or should I start new thread for this?): How do I get the parameter description into the adoc?

**Comment by RobWin** [comment]
Can you give me an example?

**Comment by tdtappe** [comment]
Sure. Given the example above and include a parameter description:

```
 "/MeasuringPointService/getMeasuringPoint" : {
      "post" : {
        "summary" : "getMeasuringPoint",
        "description" : "Measuring point object for the provided measuring point id",
        "operationId" : "getMeasuringPoint",
        "parameters" : [ {
          "name" : "id",
          "in" : "body",
          "description" : "Unique id of the measuring point",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/MeasuringPoint"
            }
          }
        }
      }
    }
```

**Comment by RobWin** [comment]
Descriptions of parameters should be included automatically. 
See description in Body parameter: http://swagger2markup.github.io/spring-swagger2markup-demo/1.1.0/#_parameters

**Comment by tdtappe** [comment]
Hmm. Strange. I just did it again without any modifications... and now it worked.
Most probably something wasn't update to date.
Anyway - it works! :-)

Thanks again. Especially for your quick responses!!!

--Heiko

**Comment by RobWin** [comment]
You are welcome, would love to get your github stars :)

**Comment by tdtappe** [comment]
Sure. You deserve it!
