### ISSUE TITLE
maven compile question

### ISSUE THREAD

**Issue by HEWU10** [Swagger2Markup/swagger2markup-maven-plugin#37]
Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.3:convertSwagger2markup (default) on project timevale-open: Execution default of goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.3:convertSwagger2markup failed: Plugin io.github.swagger2markup:swagger2markup-maven-plugin:1.3.3 or one of its dependencies could not be resolved: The following artifacts could not be resolved: nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0, ch.netzwerg:paleo-core:jar:0.10.2: Could not transfer artifact nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:jar:1.0 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.24.215] failed: Connection timed out: connect -> [Help 1]

**Comment by RobWin** [comment]
Please see docs: http://swagger2markup.github.io/swagger2markup/1.3.1/#_release
You have to add the jcenter repo.

**Comment by hannes-angst** [comment]
If any one else like me searched for this error and finally ended up here please give a thumbs up :) 

### Fix

Since you are using a plugin, you need to define the plugin repository (and not like me the repository)

```
    <pluginRepositories>
        <pluginRepository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>jcenter-releases</id>
            <name>jcenter</name>
            <url>https://jcenter.bintray.com/</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by RobWin** [comment]
Thanks.
I has been updated -> https://github.com/Swagger2Markup/swagger2markup-maven-plugin/blob/master/pom.xml#L88

**Comment by yeyeyerman** [comment]
The `pom.xml` excerpt in the [doc](http://swagger2markup.github.io/swagger2markup/1.3.3/#_maven) is wrong. It should use `https`, as pointed out by @hannes-angst:

```xml
  <repositories>
    <repository>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>jcenter-releases</id>
      <name>jcenter</name>
      <url>https://jcenter.bintray.com</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>io.github.swagger2markup</groupId>
      <artifactId>swagger2markup</artifactId>
      <version>1.3.3</version>
    </dependency>
  </dependencies>
```

Otherwise, I was receiving a 403 HTTP code.
