### ISSUE TITLE
Support setting directories for property 'swaggerInput'

### ISSUE THREAD

**Issue by marcelstoer** [Swagger2Markup/swagger2markup-maven-plugin#41]
It's rather limiting that [`swaggerInput`](https://swagger2markup.github.io/swagger2markup/1.3.1/#_configuration_3) cannot be the path to a folder that contains Swagger files. True, the plugin can be configured multiple times as a workaround but that's really ugly.

Ideally I could set a directory for `swaggerInput` and have the plugin deep-scan it for Swagger files.

**Comment by RobWin** [comment]
Would you like to contribute this functionality?

**Comment by marcelstoer** [comment]
I work with open-source extensively, mostly on GitHub. Hence, I half expected this to be the first initial comment 😜 

I'm thinking about it as I definitely have to implement this functionality anyhow.

**Comment by RobWin** [comment]
😁👍

**Comment by marcelstoer** [comment]
@RobWin it'd be helpful to me if you could me an indication whether the PR meets your expectations. And if so, in what time frame can you image merging it to release a new version? That would allow us to assess whether we need to temporarily deploy my fork for the time being.

**Comment by RobWin** [comment]
Thx. Could you please add a test to show what happens when two Swagger files (swagger1.json and swagger2.json) reside in the same folder like `/docs/swagger`?
I think we should generate sub folder based on the name of the Swagger spec file? What do you think.

**Comment by marcelstoer** [comment]
Good point, that use case is currently not supported (i.e. markdown files would get overwritten). 

> I think we should generate sub foldesr based on the name of the Swagger spec file?

Yes, something like that - but only if there really _are_ multiple files in the same folder. Otherwise the directory structure in the output dir is too deeply nested. I'll take a stab at it later today.

**Comment by RobWin** [comment]
The tests seem to fail on windows.

**Comment by RobWin** [comment]
The code seems to generate a strage URI:
```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 85: C:\Users\robwi\Documents\projects\swagger2markup-maven-plugin\target\generated-docs\C:\Users\robwi\Documents\projects\swagger2markup-maven-plugin\src\test\resources\docs\swagger\swagger.json\swagger
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at io.github.swagger2markup.Swagger2MarkupMojo.swaggerToMarkup(Swagger2MarkupMojo.java:106)
```

**Comment by marcelstoer** [comment]
Sorry, had to get a hold of a Windows environment first. I'm glad you seem to have tried to release from a Windows box otherwise this bug would likely have slipped.

**Comment by RobWin** [comment]
V1.3.4 has been released. Would you like to verify it that it works.
Sometimes I have issues to generate the correct maven plugin files. :(

**Comment by marcelstoer** [comment]
> Sometimes I have issues to generate the correct maven plugin files

Indeed, you released from the "wrong" revision. https://github.com/Swagger2Markup/swagger2markup-maven-plugin/releases/tag/v1.3.4 shows that there are "3 commits to master since this release" with one of which being the essential fix.

**Comment by RobWin** [comment]
The release contains the commits. I tagged too early. I corrected it.
The new tag contains your commits as well: https://github.com/Swagger2Markup/swagger2markup-maven-plugin/blob/v1.3.4/src/main/java/io/github/swagger2markup/Swagger2MarkupMojo.java#L119
