### ISSUE TITLE
SNAPSHOTs not updating

### ISSUE THREAD

**Issue by muddysteel** [Swagger2Markup/swagger2markup-maven-plugin#45]
CI is not pushing updated SNAPSHOT builds to:

http://oss.jfrog.org/artifactory/oss-snapshot-local/io/github/swagger2markup/swagger2markup-maven-plugin/

**Comment by RobWin** [comment]
Works again: https://oss.jfrog.org/oss-snapshot-local/io/github/swagger2markup/swagger2markup-maven-plugin

**Comment by muddysteel** [comment]
Tks!!!
