### ISSUE TITLE
1.3.6 broken due to invalid plugin descriptor

### ISSUE THREAD

**Issue by marcelstoer** [Swagger2Markup/swagger2markup-maven-plugin#49]
https://github.com/Swagger2Markup/swagger2markup-maven-plugin/blob/master/src/main/resources/META-INF/maven/plugin.xml#L10 still says 1.3.4. Maven refuses to execute it:

> [ERROR] Invalid plugin descriptor for io.github.swagger2markup:swagger2markup-maven-plugin:1.3.6 (/Users/marcelstoer/.m2/repository/io/github/swagger2markup/swagger2markup-maven-plugin/1.3.6/swagger2markup-maven-plugin-1.3.6.jar), Plugin's descriptor contains the wrong version: 1.3.4 -> [Help 1]

**Comment by RobWin** [comment]
Narf. I don't like the maven plugin :(

**Comment by marcelstoer** [comment]
Couldn't you automate this by replacing the hard coded version with `${project.version}` in `plugin.xml` and then adding the file to the filtered resource set?

**Comment by RobWin** [comment]
Yes, I once created a task which should generate the maven descriptor.
```task pluginDescriptor(type: Exec) {
    commandLine 'mvn', '-e', '-B', 'install', 'org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor', '-DskipTests'
}```
But something is not working correctly.
Would you like to have a look at it?

**Comment by RobWin** [comment]
v1.3.7 is released

**Comment by marcelstoer** [comment]
Oh, only just now do I see that you build with Gradle - not something I'm familiar with yet. So you have to keep the version in sync in three places: `build.gradle`, `pom.xml` and `plugin.xml`?

**Comment by RobWin** [comment]
Not pom.xml
Maven isn't used anymore.

**Comment by RobWin** [comment]
Releasing Swagger2Markup is anyway too cumbersome.
Too many different git repositories. I think I have to merge them into one and create a multi-module project.

**Comment by marcelstoer** [comment]
> Maven isn't used anymore.

Then why is there a `pom.xml` in the repo? Did you simply forget to delete it?

> Too many different git repositories.

I agree, I was quite surprised when I realized how complicated the setup is.

**Comment by RobWin** [comment]
Yes, the project grew step by step. Now it's really time to merge them.
No I did not forget to remove it. I always thought it might be better to build the plugin via maven, but I never really had time to do configure the maven release process to bintray. Shouldn't be too hard. But work and resilience4j had my focus.
