### ISSUE TITLE
Process multiple swagger-group-name.json files in separate folders

### ISSUE THREAD

**Issue by Valijon** [Swagger2Markup/swagger2markup-maven-plugin#55]
Our project has several views (Docket) to generate Swagger PDF files.
It would be nice if [iterator-maven-plugin](https://github.com/khmarbaise/iterator-maven-plugin) works, but it is not supported by your plugin.

Discussed here #23, It's not supported anymore multiple swagger files to generate separated pdf file.

But, I found the trick: Create separate maven profile with different `swaggerInput`.
Even `Effective POM` points correct file, during execution, it always takes same input file for all executions. Why?

I can contribute if you guide me ;-)
Thanks

**Comment by Valijon** [comment]
Didn't know if you put as `swaggerInput` a directory with `swagger.json` files, it does the magic.

Thanks for plugin

**Comment by RobWin** [comment]
You are welcome

**Comment by MilanDi90** [comment]
> Didn't know if you put as `swaggerInput` a directory with `swagger.json` files, it does the magic.
> 
> Thanks for plugin

Can you share what trick which has worked for processing multiple swagger.json files for different groups
