### ISSUE TITLE
Transfer ownership into Swagger2markup Organisation?

### ISSUE THREAD

**Issue by RobWin** [Swagger2Markup/swagger2markup-maven-plugin#6]
Do you want to transfer ownership into the Swagger2markup Organisation?

**Comment by redowl** [comment]
Sounds like a great idea! I don't know exactly what that entails, but I can
take a look on Monday.

On Saturday, October 24, 2015, Robert Winkler <notifications@github.com>
wrote:

> Do you want to transfer ownership into the Swagger2markup Organisation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redowl/swagger2markup-maven-plugin/issues/6>.
>
> --
> You received this message because you are subscribed to the Google Groups
> "External Engineering" group.
> Visit this group at
> http://groups.google.com/a/redowlanalytics.com/group/engineers/.
>


-- 
Russell Snyder
1111 Light Street, Suite 250
Baltimore, MD 21230
russ@redowlanalytics.com
727-366-8386
*REDOWL ANALYTICS* | *www.redowlanalytics.com
<http://www.redowlanalytics.com/>*

*Important Notice:*  The information contained in or attached to this email
message is confidential and proprietary information of RedOwl Analytics,
Inc., and by opening this email or any attachment the recipient agrees to
keep such information strictly confidential and not to use or disclose the
information other than as expressly authorized by RedOwl Analytics, Inc.
If you are not the intended recipient, please be aware that any use,
printing, copying, disclosure, dissemination, or the taking of any act in
reliance on this communication or the information contained herein is
strictly prohibited. If you think that you have received this email message
in error, please delete it and notify the sender.

-- 
*Important Notice:*  The information contained in or attached to this email 
message is confidential and proprietary information of RedOwl Analytics, 
Inc., and by opening this email or any attachment the recipient agrees to 
keep such information strictly confidential and not to use or disclose the 
information other than as expressly authorized by RedOwl Analytics, Inc. 
 If you are not the intended recipient, please be aware that any use, 
printing, copying, disclosure, dissemination, or the taking of any act in 
reliance on this communication or the information contained herein is 
strictly prohibited. If you think that you have received this email message 
in error, please delete it and notify the sender.

**Comment by RobWin** [comment]
https://help.github.com/articles/transferring-a-repository/

I would add you to the team then.

**Comment by RobWin** [comment]
Thx for push grants. But I mean a transfer of the ownership to swagger2markup so that the project is listed under the Organisation,

**Comment by redowl** [comment]
Oh I know - feel free to add Redowl to the org and I'll transfer ownership over!

**Comment by RobWin** [comment]
I created a team and invited you.

**Comment by RobWin** [comment]
You have to transfer the ownership to me so that I can transfer it to Swagger2markup and give you Team admin rights.
We did the same with Swagger2markup-CLI yesterday.

**Comment by redowl** [comment]
Done!  Apologies for the delay, I was on travel!

**Comment by RobWin** [comment]
Thx
