### ISSUE TITLE
Missing plugin.xml

### ISSUE THREAD

**Issue by librucha** [Swagger2Markup/swagger2markup-maven-plugin#9]
Hi.
When I tried use your plugin from maven central repo http://search.maven.org/#artifactdetails%7Cio.github.robwin%7Cswagger2markup-maven-plugin%7C0.9.1%7Cjar

```xml
<plugin>
    <groupId>io.github.robwin</groupId>
    <artifactId>swagger2markup-maven-plugin</artifactId>
    <version>0.9.1</version>
    <executions>
        <execution>
            <id>output-swagger</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>process-swagger</goal>
            </goals>
            <configuration>
                <inputDirectory>${basedir}/src/main/resources/static/v2/</inputDirectory>
                <outputDirectory>${generated.swagger.directory}</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I got this error:

Failed to parse plugin descriptor for io.github.robwin:swagger2markup-maven-plugin:0.9.1 (/home/librucha/.m2/repository/io/github/robwin/swagger2markup-maven-plugin/0.9.1/swagger2markup-maven-plugin-0.9.1.jar): No plugin descriptor found at META-INF/maven/plugin.xml

**Comment by RobWin** [comment]
Hi,

thx. I have a look at it.

**Comment by RobWin** [comment]
In the meantime you can use an older version:

```
	<groupId>com.redowlanalytics</groupId>
	<artifactId>swagger2markup-maven-plugin</artifactId>
	<version>0.7.1</version>
```

**Comment by atomfrede** [comment]
@RobWin I don't think it has something to do with the missing plugin.xml but https://github.com/Swagger2Markup/swagger2markup-maven-plugin/blob/master/gradle/publishing.gradle#L9 looks not correct to me. Shouldn't it be ``swagger2markup-maven-plugin``?

**Comment by RobWin** [comment]
Thx. I change that

**Comment by atomfrede** [comment]
@RobWin It is not perfect yet and far from an optimal solution, but I generated the [plugin xml with maven](https://github.com/atomfrede/swagger2markup-maven-plugin/commit/f56a1bf9b6cb766b7d3aa8fe644f62ec7fabb0dc) (can also be done with the new gradle task) and add it to resource directory. It is templated (right now only with project version number) during jar creation, maybe thats a way to go if you want to stay with gradle for this plugin.

**Comment by RobWin** [comment]
Thx I have a look at it.

**Comment by RobWin** [comment]
Do you want to create a PR?

**Comment by atomfrede** [comment]
No problem.

**Comment by atomfrede** [comment]
Just for everyones info, latest changes makes the plugin nearly working. Now I've got the problem that something is messing up the class file when using ``publishMavenLocal``. I've used the jar file created via maven and everything is fine. Using the jar file created and published via gradle result in ``Incompatible magic value 4022320623 in class file`` error.
